#include "../runtime/scriptRuntime.h"
#include "../runtime/standardLibrary.h"
#include "../graphs/idgeneration.h"
#include "../graphs/nodeRegistry.h"
#include "../script/scriptSerializer.h"

#include <iostream>
#include <string>

namespace
{
void PrintUsage()
{
    std::cout
        << "Visual Lox CLI\n\n"
        << "Usage:\n"
        << "  visual-lox-cli [--disassemble] <script.vlox>\n\n"
        << "Options:\n"
        << "  --disassemble  Print generated bytecode before execution.\n"
        << "  -h, --help     Show this help.\n";
}
}

int main(int argc, char** argv)
{
    bool disassemble = false;
    std::string scriptPath;
    for (int i = 1; i < argc; ++i)
    {
        const std::string argument = argv[i];
        if (argument == "-h" || argument == "--help")
        {
            PrintUsage();
            return 0;
        }
        if (argument == "--disassemble")
        {
            disassemble = true;
            continue;
        }
        if (!scriptPath.empty())
        {
            std::cerr << "Only one .vlox file can be executed at a time.\n";
            return 2;
        }
        scriptPath = argument;
    }

    if (scriptPath.empty())
    {
        PrintUsage();
        return 2;
    }

    VM& vm = VM::getInstance();
    NodeRegistry registry;
    RegisterStandardLibrary(registry);
    registry.RegisterNatives(vm);

    Script script;
    IDGenerator ids;
    vm.setExternalMarkingFunc([&]()
    {
        MarkNodeRegistryRoots(registry, vm);
        ScriptUtils::MarkScriptRoots(script);
    });

    const SerializationResult loadResult = ScriptSerializer::Load(scriptPath, registry, script, ids);
    if (!loadResult)
    {
        std::cerr << "Could not load '" << scriptPath << "': " << loadResult.error << '\n';
        return 2;
    }

    ScriptCompileOptions options;
    options.disassemble = disassemble;
    const ScriptCompileResult compileResult = ScriptRuntime::Compile(vm, script, options);
    if (!compileResult)
    {
        std::cerr << "Visual Lox compilation failed.\n";
        return 3;
    }

    const InterpretResult result = ScriptRuntime::Execute(vm, compileResult.function);
    if (result == InterpretResult::INTERPRET_RUNTIME_ERROR)
        return 4;
    if (result != InterpretResult::INTERPRET_OK)
        return 3;
    return 0;
}
