#include "../runtime/scriptRuntime.h"
#include "../runtime/standardLibrary.h"
#include "../graphs/idgeneration.h"
#include "../graphs/nodeRegistry.h"
#include "../script/scriptSerializer.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <system_error>
#include <utility>
#include <vector>

namespace
{
void PrintUsage()
{
    std::cout
        << "Visual Lox CLI\n\n"
        << "Usage:\n"
        << "  vlox [--disassemble] <script.vlox> [arguments...]\n"
        << "  vlox migrate --check <script.vlox>\n"
        << "  vlox migrate --write <script.vlox>\n"
        << "  vlox inspect-definitions\n"
        << "  vlox validate --json <script.vlox>\n\n"
        << "Options:\n"
        << "  --disassemble  Print generated bytecode before execution.\n"
        << "  --check        Preview whether a document needs migration.\n"
        << "  --write        Migrate in place and retain a backup.\n"
        << "  -h, --help     Show this help.\n";
}

int InspectDefinitions()
{
    VM& vm = VM::getInstance();
    NodeRegistry registry;
    RegisterStandardLibrary(registry);
    registry.RegisterNatives(vm);

    struct DefinitionSummary
    {
        std::string id;
        uint32_t revision = 1;
        std::string fingerprint;
        std::string displayName;
    };
    std::vector<DefinitionSummary> definitions;
    definitions.reserve(registry.nativeDefinitions.size() + registry.compiledDefinitions.size());
    for (const NativeFunctionDef& native : registry.nativeDefinitions)
        if (native.functionDef)
            definitions.push_back({ native.functionDef->id, native.functionDef->revision, native.functionDef->compatibilityFingerprint, native.functionDef->name });
    for (const CompiledNodeDefPtr& compiled : registry.compiledDefinitions)
        if (compiled && compiled->functionDef)
            definitions.push_back({ compiled->id, compiled->revision, compiled->functionDef->compatibilityFingerprint, compiled->name });
    std::sort(definitions.begin(), definitions.end(), [](const DefinitionSummary& left, const DefinitionSummary& right) { return left.id < right.id; });

    std::cout << "definition_id\trevision\tfingerprint\tdisplay_name\n";
    for (const DefinitionSummary& definition : definitions)
        std::cout << definition.id << '\t' << definition.revision << '\t' << definition.fingerprint << '\t' << definition.displayName << '\n';
    return 0;
}

std::string EscapeJson(const std::string& value)
{
    std::string result;
    result.reserve(value.size() + 2);
    for (const unsigned char character : value)
    {
        switch (character)
        {
        case '"': result += "\\\""; break;
        case '\\': result += "\\\\"; break;
        case '\b': result += "\\b"; break;
        case '\f': result += "\\f"; break;
        case '\n': result += "\\n"; break;
        case '\r': result += "\\r"; break;
        case '\t': result += "\\t"; break;
        default:
            if (character < 0x20)
            {
                constexpr char hex[] = "0123456789abcdef";
                result += "\\u00";
                result += hex[character >> 4];
                result += hex[character & 0x0f];
            }
            else
            {
                result += static_cast<char>(character);
            }
            break;
        }
    }
    return result;
}

int ValidateDocumentJson(int argc, char** argv)
{
    if (argc != 4 || std::string(argv[2]) != "--json")
    {
        PrintUsage();
        return 2;
    }

    VM& vm = VM::getInstance();
    NodeRegistry registry;
    RegisterStandardLibrary(registry);
    registry.RegisterNatives(vm);
    Script script;
    IDGenerator ids;
    vm.setExternalMarkingFunc([&]()
    {
        MarkNodeRegistryRoots(registry, vm);
        ScriptUtils::MarkScriptRoots(script);
    });

    const SerializationResult loaded = ScriptSerializer::Load(argv[3], registry, script, ids);
    ScriptCompileResult compiled;
    if (loaded) compiled = ScriptRuntime::Compile(vm, script, {});
    const bool valid = loaded && static_cast<bool>(compiled);
    std::cout << "{\"valid\":" << (valid ? "true" : "false") << ",\"diagnostics\":[";
    bool first = true;
    const auto separator = [&]()
    {
        if (!first) std::cout << ',';
        first = false;
    };
    for (const SerializationDiagnostic& diagnostic : loaded.diagnostics)
    {
        separator();
        const char* severity = diagnostic.severity == SerializationDiagnosticSeverity::Error ? "error"
            : diagnostic.severity == SerializationDiagnosticSeverity::Warning ? "warning" : "info";
        std::cout << "{\"severity\":\"" << severity << "\",\"code\":\"" << EscapeJson(diagnostic.code) << "\",\"path\":\""
                  << EscapeJson(diagnostic.path) << "\",\"identity\":\"" << EscapeJson(diagnostic.identity) << "\",\"message\":\""
                  << EscapeJson(diagnostic.message) << "\"}";
    }
    for (const ValidationDiagnostic& diagnostic : compiled.validation.diagnostics)
    {
        separator();
        std::cout << "{\"severity\":\"" << (diagnostic.severity == DiagnosticSeverity::Error ? "error" : "warning") << "\",\"code\":\""
                  << EscapeJson(diagnostic.code) << "\",\"path\":\"" << EscapeJson(diagnostic.graphName) << "\",\"identity\":\"node:"
                  << diagnostic.nodeId.Get() << "\",\"message\":\"" << EscapeJson(diagnostic.message) << "\"}";
    }
    std::cout << "]}\n";
    return valid ? 0 : 3;
}

void PrintDiagnostic(const SerializationDiagnostic& diagnostic)
{
    const char* severity = diagnostic.severity == SerializationDiagnosticSeverity::Error ? "error"
        : diagnostic.severity == SerializationDiagnosticSeverity::Warning ? "warning" : "info";
    std::cout << severity << " [" << diagnostic.code << "]";
    if (!diagnostic.path.empty()) std::cout << " " << diagnostic.path;
    std::cout << ": " << diagnostic.message << '\n';
}

std::filesystem::path UniqueSiblingPath(const std::filesystem::path& source, const std::string& suffix)
{
    std::filesystem::path candidate = source;
    candidate += suffix;
    for (int number = 1; std::filesystem::exists(candidate); ++number)
    {
        candidate = source;
        candidate += suffix + "." + std::to_string(number);
    }
    return candidate;
}

bool ReadTextFile(const std::filesystem::path& path, std::string& output)
{
    std::ifstream input(path, std::ios::binary);
    if (!input) return false;
    std::ostringstream contents;
    contents << input.rdbuf();
    output = contents.str();
    return input.good() || input.eof();
}

bool WriteTextFile(const std::filesystem::path& path, const std::string& contents)
{
    std::ofstream output(path, std::ios::binary | std::ios::trunc);
    output.write(contents.data(), static_cast<std::streamsize>(contents.size()));
    output.put('\n');
    return output.good();
}

int MigrateDocument(int argc, char** argv)
{
    if (argc != 4 || (std::string(argv[2]) != "--check" && std::string(argv[2]) != "--write"))
    {
        PrintUsage();
        return 2;
    }

    const bool write = std::string(argv[2]) == "--write";
    const std::filesystem::path source = argv[3];
    std::string original;
    if (!ReadTextFile(source, original))
    {
        std::cerr << "Could not read '" << source.string() << "'.\n";
        return 2;
    }

    std::string migrated;
    VM& vm = VM::getInstance();
    NodeRegistry registry;
    RegisterStandardLibrary(registry);
    registry.RegisterNatives(vm);
    const SerializationResult result = ScriptSerializer::MigrateToCurrentFormat(original, registry, migrated);
    for (const SerializationDiagnostic& diagnostic : result.diagnostics) PrintDiagnostic(diagnostic);
    if (!result)
    {
        std::cerr << "Migration failed: " << result.error << '\n';
        return 2;
    }

    if (result.diagnostics.empty())
    {
        std::cout << "Document is already at format version " << ScriptSerializer::FormatVersion << ".\n";
        return 0;
    }
    if (!write)
    {
        std::cout << "Migration is available; no files were changed.\n";
        return 0;
    }

    const std::filesystem::path temporary = UniqueSiblingPath(source, ".migrating");
    const std::filesystem::path backup = UniqueSiblingPath(source, ".bak");
    if (!WriteTextFile(temporary, migrated))
    {
        std::error_code ignored;
        std::filesystem::remove(temporary, ignored);
        std::cerr << "Could not write migration temporary file '" << temporary.string() << "'.\n";
        return 2;
    }

    std::error_code error;
    std::filesystem::rename(source, backup, error);
    if (error)
    {
        std::filesystem::remove(temporary, error);
        std::cerr << "Could not create backup '" << backup.string() << "'.\n";
        return 2;
    }
    std::filesystem::rename(temporary, source, error);
    if (error)
    {
        std::error_code recoveryError;
        std::filesystem::rename(backup, source, recoveryError);
        std::error_code cleanupError;
        std::filesystem::remove(temporary, cleanupError);
        std::cerr << "Could not replace the document after migration.";
        if (recoveryError) std::cerr << " The original remains at '" << backup.string() << "'.";
        std::cerr << '\n';
        return 2;
    }

    std::cout << "Migrated '" << source.string() << "'. Backup: '" << backup.string() << "'.\n";
    return 0;
}
}

int main(int argc, char** argv)
{
    if (argc >= 2 && std::string(argv[1]) == "migrate") return MigrateDocument(argc, argv);
    if (argc == 2 && std::string(argv[1]) == "inspect-definitions") return InspectDefinitions();
    if (argc >= 2 && std::string(argv[1]) == "validate") return ValidateDocumentJson(argc, argv);

    bool disassemble = false;
    std::string scriptPath;
    std::vector<std::string> programArguments;
    for (int i = 1; i < argc; ++i)
    {
        const std::string argument = argv[i];
        if (!scriptPath.empty())
        {
            programArguments.push_back(argument);
            continue;
        }
        if (argument == "-h" || argument == "--help")
        {
            PrintUsage();
            return 0;
        }
        if (argument == "--disassemble")
        {
            disassemble = true;
            continue;
        }
        scriptPath = argument;
    }

    if (scriptPath.empty())
    {
        PrintUsage();
        return 2;
    }

    VM& vm = VM::getInstance();
    NodeRegistry registry;
    RegisterStandardLibrary(registry);
    registry.RegisterNatives(vm);

    Script script;
    IDGenerator ids;
    vm.setExternalMarkingFunc([&]()
    {
        MarkNodeRegistryRoots(registry, vm);
        ScriptUtils::MarkScriptRoots(script);
    });

    const SerializationResult loadResult = ScriptSerializer::Load(scriptPath, registry, script, ids);
    if (!loadResult)
    {
        std::cerr << "Could not load '" << scriptPath << "': " << loadResult.error << '\n';
        return 2;
    }

    ScriptCompileOptions options;
    options.disassemble = disassemble;
    options.programArguments = std::move(programArguments);
    const ScriptCompileResult compileResult = ScriptRuntime::Compile(vm, script, options);
    for (const ValidationDiagnostic& diagnostic : compileResult.validation.diagnostics)
    {
        std::ostream& output = diagnostic.severity == DiagnosticSeverity::Error ? std::cerr : std::clog;
        output << FormatDiagnostic(diagnostic) << '\n';
    }
    if (!compileResult)
    {
        std::cerr << "Visual Lox compilation failed.\n";
        return 3;
    }

    const InterpretResult result = ScriptRuntime::Execute(vm, compileResult.function);
    if (result == InterpretResult::INTERPRET_RUNTIME_ERROR)
        return 4;
    if (result != InterpretResult::INTERPRET_OK)
        return 3;
    return 0;
}
